# Generated by Django 5.2.8 on 2026-05-20 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='grade',
            new_name='student_class',
        ),
    ]
